feature/9/tags
popeskul/quest-custom-ror pull request #11
Opened 2021-11-03 23:40 UTC by popeskul

2021-11-04 07:44 UTC, Mehonoshin requested changes

2021-11-04 07:44 UTC, Mehonoshin commented on app/assets/stylesheets/admin/tags.scss
> +// Place all the styles related to the Admin::Tags controller here.
удаляем этот файл

2021-11-04 07:44 UTC, Mehonoshin commented on app/controllers/events_controller.rb
> +    @tags = helpers.all_tags
хелперы предназначены для использования во view.
не нужно их использовать в контроллере таким образом

2021-11-04 07:44 UTC, Mehonoshin commented on app/controllers/admin/tags_controller.rb
> +      @tag = helpers.new_tag
не используем хелперы в контроллере

2021-11-04 07:44 UTC, Mehonoshin commented on app/services/services/search_by_tags.rb
> +      @text.scan(/\b#{transformed_tags}\b/i)
В задании говорится:
> Например, при нахождении слова docker в тексте, мероприятию присваивается тег devops.

Не вижу реализации подобного кейса.

2021-11-04 21:16 UTC, popeskul commented on app/services/services/search_by_tags.rb
> +      @text.scan(/\b#{transformed_tags}\b/i)
Переделал логику

2021-11-05 08:48 UTC, Mehonoshin commented on app/services/services/create_tag.rb
> +      @tag
в чем смысл этого класса, если в нем не происходит save ?)

2021-11-05 13:25 UTC, merged